### ISSUE TITLE
Help with refactor ESP32 support

### ISSUE THREAD

**Issue by pablogs9** [micro-ROS/freertos_apps#19]
Hello @donRaphaco, I'm removing the libatomic from the extensions repositories and adding it to `rcutils` package, check this: https://github.com/micro-ROS/micro_ros_setup/pull/171/checks?check_run_id=953530520

But in the case of the ESP32 I'm not able to remove the folder `components/libatomics` and [these two lines](https://github.com/micro-ROS/freertos_apps/blob/121082154079ac72751b0d55ec190aa28de89664/microros_esp32_extensions/main/CMakeLists.txt#L40-L41) without having building errors.

Is possible for you to remove this libatomic dependency for the ESP32 board support? I'm working in this PR: https://github.com/micro-ROS/freertos_apps/pull/18 You can commit there if you wish.

Thanks!

**Comment by donRaphaco** [comment]
It should be fixed with 5c87578
