### ISSUE TITLE
Can not change UART3 to UART1

### ISSUE THREAD

**Issue by allstarry** [micro-ROS/freertos_apps#25]
ros2 run micro_ros_setup configure_firmware.sh ping_pong --transport serial --dev 1
After execute this and build the firmware, ROS can still get message from UART3 instead of UART1.
It seems that only UART3 has DMA configured in stm32f4xx_hal_msp.c.

**Comment by pablogs9** [comment]
Please detail which is your setup and which are the board you are using.

**Comment by pablogs9** [comment]
Reopen if still active issue.
