### ISSUE TITLE
Use C++ to write app

### ISSUE THREAD

**Issue by ncnynl** [micro-ROS/freertos_apps#47]
I have passed the test, freertos app's ping_pong, I would like to ask if there is an example of changing app.c to app.cpp. Under keil IDE under ros1, I can integrate cpp classes into my code. But under the micro-ros, it has not been tested by adding the cpp file.

**Comment by ncnynl** [comment]
At present, the problem of integrating C++ has been basically solved. Makefile adds C++ support, retains app.c and adds a func.h and func.cpp to specifically dock C++ classes. Func.cpp is used to call C++ classes and library files, and to write C standard functions, app .c Pass related parameters or perform specific operations by calling related functions of func.cpp.

In this way, the LED flicker test can now be controlled.

**Comment by pablogs9** [comment]
Is this issue resolved? If so, close please
