### ISSUE TITLE
UDP transport failed by ethernet port  in ping_pong example with freeRTOS on olimexe407 board.

### ISSUE THREAD

**Issue by JONDOE290** [micro-ROS/freertos_apps#49]
the configure I used :
        ros2 run micro_ros_setup configure_firmware.sh ping_pong -t udp -i 192.168.0.181 -p 8888 
        ros2 run micro_ros_agent micro_ros_agent udp4 --port 8888 -v 6

and change the IP addresses in lwip.c:
        void MX_LWIP_Init(void)
        {
          /* Initilialize the LwIP stack with RTOS */
          tcpip_init( NULL, NULL );
          osThreadAttr_t attributes;
          ipaddr.addr = 0xC0A800B5;//192.168.0.181
          netmask.addr = 0xFFFFFF00;//255.255.255.0
          gw.addr = 0xC0A80001;//192.168.0.1
    ......

it builds and works:
          [1610689478.070872] info     | UDPv4AgentLinux.cpp | init                     | running...             | port: 8888
          [1610689478.071353] info     | Root.cpp           | set_verbose_level        | logger setup           | verbose_level: 4
and the port8888:
          COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
          micro_ros 4579   xu    4u  IPv4  71317      0t0  UDP *:8888 
but win i ping 192.168.0.181,it shows:
          From 192.168.0.180 icmp_seq=166 Destination Host Unreachable
and win i use:ros2 topic echo /microROS/ping
          WARNING: topic [/microROS/ping] does not appear to be published yet
          Could not determine the type for the passed topic
the uart shows:
           Ethernet Initialization␍␊
           Waiting for IP␍␊
           IP: 181.0.168.192␍␊
          UDP mode => ip: 192.168.0.181 - port: 8888␊
           **********************************␊
           Task  State   Prio    Stack    Num␊
          **********************************␊
           initTask       ⇥	X⇥	23⇥	118⇥	3␍␊
           IDLE           ⇥	R⇥	0⇥	104⇥	4␍␊
          tcpip_thread   ⇥	B⇥	24⇥	149⇥	1␍␊
          microROS_app   ⇥	B⇥	25⇥	1660⇥	6␍␊
           Tmr Svc        ⇥	B⇥	2⇥	214⇥	5␍␊
          EthIf          ⇥	B⇥	48⇥	2⇥	2␍␊
          **********************************␊
          [ERROR] [ld.ld] [rclc]: [rclc_init] Error in rcl_init: error not set␊
          Failed status on line 87: 1. Aborting.␊

does olimexe407 support this configure?
or can you give me codes or settings that works?

thank you

**Comment by pablogs9** [comment]
Closing since duplicated: https://github.com/micro-ROS/freertos_apps/issues/48
