### ISSUE TITLE
Perhaps a Bug: `MX_DMA_Init();` must happens before `MX_USART3_UART_Init();`

### ISSUE THREAD

**Issue by ZhenshengLee** [micro-ROS/freertos_apps#94]
## Issue template

- Hardware description: nucleo_stm32f767zi
- RTOS: FreeRTOS
- Installation type: micro_ros_setup
- Version or commit hash: galactic

#### Steps to reproduce the issue

change `main.c` , compile and flash.

```cpp
  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_USART3_UART_Init();
  MX_DMA_Init();
  MX_USB_OTG_FS_PCD_Init();
```

#### Expected behavior

smoke test success.

#### Actual behavior

transport of serial failed, with no output of agent

#### Additional information

In auto-generated code by cubemx(6.4), `MX_DMA_Init();` happens after `MX_USART3_UART_Init();`

_Originally posted by @ZhenshengLee in https://github.com/ZhenshengLee/ros2_mcu/issues/2#issuecomment-1063611974_

**Comment by pablogs9** [comment]
Not a micro-ROS issue
