### ISSUE TITLE
[HELP WANTED] ping success but agent connection failed when udp link with stm32f767zi.

### ISSUE THREAD

**Issue by ZhenshengLee** [micro-ROS/freertos_apps#95]
## Issue template

- Hardware description: nucleo-stm32f767zi connecting a router with ip 192.168.1.110
- RTOS: FreeRTOS
- Installation type: micro_ros_setup like, the src code is in https://github.com/ZhenshengLee/ros2_mcu/tree/master/libs/custom_stm32f767zi
- Version or commit hash: galactic

#### Steps to reproduce the issue
https://github.com/ZhenshengLee/ros2_mcu/tree/master/libs/custom_stm32f767zi

compile and flash with udp configuration.
colcon.meta is https://github.com/ZhenshengLee/ros2_mcu/blob/master/mcu_ws/colcon.meta
app-colcol.meta is https://github.com/ZhenshengLee/ros2_mcu/blob/master/apps/int32_publisher/app-colcon.meta

#### Expected behavior

udp connectiong success, with agent output info.

#### Actual behavior

ping 192.168.1.110 success.

but agent output nothing with

```cpp
ros2 run micro_ros_agent micro_ros_agent udp4 -p 8000 -v6
[1646914947.040102] info     | UDPv4AgentLinux.cpp | init                     | running...             | port: 8000
[1646914947.040316] info     | Root.cpp           | set_verbose_level        | logger setup           | verbose_level: 6
```

serial output the follow

![image](https://user-images.githubusercontent.com/17764118/157662868-9b6465ee-104f-4b23-b5ef-dd601cba3e33.png)

IP is got, but `Failed status on line 37: 1. Aborting.`

which is 

```cpp
RCCHECK(rclc_support_init(&support, 0, NULL, &allocator));
```

**Comment by pablogs9** [comment]
I cannot access [https://github.com/ZhenshengLee/ros2_mcu](https://github.com/ZhenshengLee/ros2_mcu/blob/master/apps/int32_publisher/app-colcon.meta). Is it private?

**Comment by ZhenshengLee** [comment]
> I cannot access [https://github.com/ZhenshengLee/ros2_mcu](https://github.com/ZhenshengLee/ros2_mcu/blob/master/apps/int32_publisher/app-colcon.meta). Is it private?

Oh... @pablogs9 
You can access it now.

**Comment by pablogs9** [comment]
Can you check if your code is reaching [this function](https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/2195d43fff3052e3e426b8e678c682e5ffcc1cb5/src/c/profile/transport/ip/udp/udp_transport_posix_nopoll.c#L76) with a JTAG debugger?

Have you tried to run a basic UDP application?

**Comment by ZhenshengLee** [comment]
> Can you check if your code is reaching [this function](https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/2195d43fff3052e3e426b8e678c682e5ffcc1cb5/src/c/profile/transport/ip/udp/udp_transport_posix_nopoll.c#L76) with a JTAG debugger?

@pablogs9   Yes I think it's reaching the function.

![image](https://user-images.githubusercontent.com/17764118/157787168-448ddacc-e1dd-4cb1-ac17-4fb232e3f1dc.png)

I will build a minimal udp test program later.

**Comment by ZhenshengLee** [comment]
@pablogs9  problem solved 

I misunderstand the meaning of `"-DRMW_UXRCE_DEFAULT_UDP_IP=192.168.1.110"`

the host(agent) should be assigned with the IP=192.168.1.110, rather than the client (stm32 device).

closing this.

Thank you.
